/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AAlert: typeof import('ant-design-vue/es')['Alert']
    AButton: typeof import('ant-design-vue/es')['Button']
    ACascader: typeof import('ant-design-vue/es')['Cascader']
    ACheckbox: typeof import('ant-design-vue/es')['Checkbox']
    ACheckboxGroup: typeof import('ant-design-vue/es')['CheckboxGroup']
    ACol: typeof import('ant-design-vue/es')['Col']
    AConfigProvider: typeof import('ant-design-vue/es')['ConfigProvider']
    ADatePicker: typeof import('ant-design-vue/es')['DatePicker']
    ADropdown: typeof import('ant-design-vue/es')['Dropdown']
    AForm: typeof import('ant-design-vue/es')['Form']
    AFormItem: typeof import('ant-design-vue/es')['FormItem']
    AInput: typeof import('ant-design-vue/es')['Input']
    AInputGroup: typeof import('ant-design-vue/es')['InputGroup']
    AInputPassword: typeof import('ant-design-vue/es')['InputPassword']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    AMenuItem: typeof import('ant-design-vue/es')['MenuItem']
    APopover: typeof import('ant-design-vue/es')['Popover']
    Approval: typeof import('./src/components/release/approval.vue')['default']
    ARadio: typeof import('ant-design-vue/es')['Radio']
    ARadioGroup: typeof import('ant-design-vue/es')['RadioGroup']
    ARow: typeof import('ant-design-vue/es')['Row']
    ASelect: typeof import('ant-design-vue/es')['Select']
    ASelectOption: typeof import('ant-design-vue/es')['SelectOption']
    ATextarea: typeof import('ant-design-vue/es')['Textarea']
    ATooltip: typeof import('ant-design-vue/es')['Tooltip']
    FileUpdate: typeof import('./src/components/FileUpdate.vue')['default']
    HelloWord: typeof import('./src/components/HelloWord.vue')['default']
    ImgUpdata: typeof import('./src/components/ImgUpdata.vue')['default']
    ImgUpdate: typeof import('./src/components/ImgUpdate.vue')['default']
    Process: typeof import('./src/components/release/Process.vue')['default']
    ReleaseContent: typeof import('./src/components/ReleaseContent.vue')['default']
    ReleaseHeader: typeof import('./src/components/ReleaseHeader.vue')['default']
    ReleaseInfo: typeof import('./src/components/ReleaseInfo.vue')['default']
    ReleaseProgress: typeof import('./src/components/release/ReleaseProgress.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SqlUpdate: typeof import('./src/components/SqlUpdate.vue')['default']
    SvgIcon: typeof import('./src/components/SvgIcon.vue')['default']
  }
}
